name: Java/Gradle CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  lines-of-code:
    runs-on: ubuntu-latest
    steps:
    # Count line numbers and language usages
    - name: Count Lines of Code (cloc)
      uses: djdefi/cloc-action@2
  
  # This workflow contains a single job called "build-GitHub-Actions"
  build-GH-Actions:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: Gradle Android
      uses: Raul6469/android-gradle-action@2.0.0
      with:
        script: dist:desktop

    - name: Cache Gradle packages
      uses: actions/cache@v2
      with:
        path: ~/.gradle/caches
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
        restore-keys: ${{ runner.os }}-gradle
      
    # To upload built file to inspect later
    - name: Publish package
      uses: actions/upload-artifact@v2
      with:
        name: Package
        path: build/libs